function  figure_gen_noise_cov_brain_fig(current_dir, algo_name, method, sa, cm17a, Weight,noise_cov)

close all
figure('units','normalized','outerposition',[0 0 0.65 0.85])
% figure('Units', 'pixels', 'outerposition', [0 0 0.65*3840 0.85*2160]);
amp_origin = sqrt(sum(Weight.^2, 2));
amp_origin = amp_origin ./ sum(amp_origin);
plot((1:size(Weight,1)),amp_origin);
hXLabel = xlabel('Voxel index', 'FontSize', 40);
hYLabel = ylabel('Amplitude', 'FontSize', 40);
set(gca(),'XLim',[1 size(Weight,1)]);
drawnow

set(gca, ...
'Box'         , 'off'     , ...
'TickDir'     , 'in'     , ...
'YMinorTick'  , 'on'      , ...
'TickLength'  , [.01 .05] , ...
'YGrid'       , 'on'      , ...
'XMinorTick'  , 'on'      , ...
'YMinorGrid'  , 'on'      , ...
'XGrid'       , 'on'      , ...
'XMinorTick'  , 'on'      , ...
'TickLength'  , [.01 .05] , ...
'FontSize'    , 50        , ... 
'LineWidth'   , 1         );  
set(gcf,'color','w');

set(gcf,'color','w');
set( hYLabel,'FontSize', 60);
set( hXLabel, 'FontSize', 60);    

res = 100; 
file_name = [current_dir '/figures/' algo_name '/' method '/voxel-distribution']; 
mkdir(file_name)
savefig(file_name); 
export_fig(file_name, ['-r' num2str(res)], '-a2', '-transparent', '-eps', '-pdf'); 
res = 200; 
export_fig(file_name, ['-r' num2str(res)], '-nocrop', '-a2', '-transparent','-png'); 

figure('units','normalized','outerposition',[0 0 0.65 0.85])
% figure('Units', 'pixels', 'outerposition', [0 0 0.65*3840 0.85*2160]);
imagesc(real(noise_cov))
axis('equal')
axis('tight')
colorbar
drawnow
set(gca, ...
'Box'         , 'off'     , ...
'TickDir'     , 'in'     , ...
'YMinorTick'  , 'on'      , ...
'TickLength'  , [.01 .05] , ...
'YGrid'       , 'on'      , ...
'XMinorTick'  , 'on'      , ...
'YMinorGrid'  , 'on'      , ...
'XGrid'       , 'on'      , ...
'XMinorTick'  , 'on'      , ...
'TickLength'  , [.01 .05] , ...
'FontSize'    , 60        , ... 
'LineWidth'   , 1         );  
set(gcf,'color','w');

set(gcf,'color','w');
set( hYLabel,'FontSize', 50);
set( hXLabel, 'FontSize', 50); 

res = 100; 
file_name = [current_dir '/figures/' algo_name '/' method '/noise-cov'];  
mkdir(file_name)
savefig(file_name); 
export_fig(file_name, ['-r' num2str(res)], '-a2', '-transparent', '-eps', '-pdf'); 
res = 200; 
export_fig(file_name, ['-r' num2str(res)], '-nocrop', '-a2', '-transparent','-png'); 

mkdir([current_dir '/figures/' algo_name '/' method '/brain-maps']); 
amp = sqrt(sum(Weight.^2, 2));
allplots_cortex(sa, amp(sa.cortex2K.in_to_cortex75K_geod, :), ...
 [0 max(amp)], cm17a, 'A.U.', 1, [current_dir '/figures/' algo_name '/' method '/brain-maps']);
 
end

